export default function OfflineTests() {
  const features = [
    {
      title: "Infinite Variations",
      description: "Each click generates a new version of the same question, with the numbers changing but the core concept remaining the same."
    },
    {
      title: "Cheat-Proof Testing",
      description: "Ideal for live class assessments or tests, minimizing chances of copying even in crowded classrooms."
    },
    {
      title: "Mastery Through Practice",
      description: "Students can solve as many variations as needed to gain full confidence in complex NEET numericals."
    },
    {
      title: "Offline Pen-Paper Mode",
      description: "Prints personalized question papers for offline batches. Teachers upload attempted sheets for instant AI evaluation!"
    }
  ];

  return (
    <section id="offline-tests" className="py-16 md:py-24 px-6 relative overflow-hidden bg-dark-bg">
      <div className="max-w-7xl mx-auto grid lg:grid-cols-2 gap-12 md:gap-16 items-center">
        
        {/* Left Side: Content */}
        <div className="space-y-10">
          <div className="space-y-6">
            <h2 className="text-4xl md:text-5xl lg:text-6xl font-serif font-black text-white leading-tight">
              Offline Cheat Proof Tests? <span className="font-script text-brand-gold italic font-normal block mt-2">What a Power! ⚡</span>
            </h2>
            <p className="text-white/70 text-lg leading-relaxed max-w-lg">
              Dynamic question templates generated by SK Intelligence that change with every click, making assessments cheat-proof for teachers and practice limitless for students.
            </p>
          </div>

          <div className="space-y-8">
            {features.map((feature) => (
              <div key={feature.title} className="space-y-2 group">
                <h4 className="text-xl font-bold text-white group-hover:text-brand-orange transition-colors">
                  {feature.title}
                </h4>
                <p className="text-white/50 text-sm leading-relaxed max-w-md">
                  {feature.description}
                </p>
              </div>
            ))}
          </div>
        </div>

        {/* Right Side: Mockup (Practice to Perfection) */}
        <div className="relative">
          <div className="absolute inset-0 bg-brand-gold/10 blur-[120px] rounded-full animate-pulse" />
          
          <div className="relative glass-card aspect-[4/3] rounded-[2.5rem] p-3 border-white/10 shadow-2xl overflow-hidden bg-gradient-to-br from-indigo-900 to-slate-900">
            <div className="absolute inset-2 rounded-[1.8rem] flex flex-col overflow-hidden bg-[#1A1B23]">
              
              {/* UI Header */}
              <div className="h-20 flex items-center justify-center relative border-b border-white/5">
                 <div className="flex items-center gap-2">
                    <span className="text-2xl font-black text-brand-orange tracking-tighter">THE SK</span>
                    <span className="text-xs font-bold text-white/40 uppercase tracking-widest mt-1">Practice</span>
                 </div>
              </div>

              {/* Practice Area */}
              <div className="flex-1 p-8 flex flex-col items-center justify-center text-center space-y-8">
                 <h3 className="text-3xl font-serif font-black text-white">Practice to <span className="text-brand-gold italic">Perfection</span></h3>
                 
                 {/* Question Card */}
                 <div className="w-full bg-white rounded-2xl p-6 shadow-2xl space-y-6 text-left">
                    <p className="text-[10px] font-bold text-slate-800 leading-tight">
                       Which of the given values of x and y make the following matrices equal?
                    </p>
                    <div className="flex justify-center py-4">
                       <div className="flex gap-4 items-center">
                          <div className="p-2 border-2 border-slate-200 rounded text-[10px] font-mono">
                             [3x+7  5]<br/>[y+1   2-3x]
                          </div>
                          <span className="text-slate-400 font-bold">=</span>
                          <div className="p-2 border-2 border-slate-200 rounded text-[10px] font-mono">
                             [0  y-2]<br/>[8  4]
                          </div>
                       </div>
                    </div>

                    {/* Options */}
                    <div className="space-y-2">
                       {[
                         'x = -7/3, y = 8',
                         'x = -2/3, y = 7',
                         'x = -1/3, y = 8',
                         'x = -7/3, y = 5'
                       ].map((opt, i) => (
                         <div key={i} className={`p-3 border rounded-xl text-[9px] font-bold ${i === 2 ? 'border-brand-orange bg-orange-50 text-brand-orange' : 'border-slate-100 text-slate-500'}`}>
                           {i + 1}) {opt}
                         </div>
                       ))}
                    </div>
                 </div>
              </div>

              {/* Bottom Decorative Circles */}
              <div className="absolute -bottom-10 -left-10 w-40 h-40 bg-brand-orange/20 rounded-full blur-3xl" />
              <div className="absolute -bottom-20 right-10 w-60 h-60 bg-brand-gold/10 rounded-full blur-3xl" />
            </div>
          </div>
        </div>

      </div>
    </section>
  );
}
